"""Aggregate all experiment results, generate an accuracy table and one
accuracy-vs-training-size plot per (dataset, encoder) pair, and write it all
into RESULTS.md at the project root.

Usage:
    python scripts/generate_report.py
"""

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from src.evaluation.aggregation import aggregate_results, load_all_results
from src.evaluation.tables import format_accuracy_table
from src.visualization.accuracy_vs_shot import plot_accuracy_vs_shot

PROJECT_ROOT = Path(__file__).resolve().parent.parent


def main() -> None:
    output_dir = PROJECT_ROOT / "outputs"
    reports_dir = PROJECT_ROOT / "reports"
    figures_dir = reports_dir / "figures"

    records = load_all_results(output_dir)
    print(f"Loaded {len(records)} individual run results from {output_dir}")
    if not records:
        raise RuntimeError(
            f"No result.json files found under {output_dir}. Run scripts/run_linear_probe.py "
            "and/or scripts/run_prototype.py first."
        )

    summaries = aggregate_results(records)
    print(f"Aggregated into {len(summaries)} (dataset, encoder, method, k_shot) settings")

    table_markdown = format_accuracy_table(summaries)

    dataset_encoder_pairs = sorted({(s["dataset"], s["encoder"]) for s in summaries})
    figure_relative_paths = []
    for dataset, encoder in dataset_encoder_pairs:
        figure_path = figures_dir / f"accuracy_vs_shot_{dataset}_{encoder}.png"
        plot_accuracy_vs_shot(summaries, dataset, encoder, figure_path)
        figure_relative_paths.append((dataset, encoder, figure_path.relative_to(PROJECT_ROOT)))
        print(f"Saved {figure_path}")

    report_lines = [
        "# Stage 1 Results\n",
        "Auto-generated by `scripts/generate_report.py` from `outputs/`. "
        "Re-run that script after new experiments to refresh this file.\n",
        "## Accuracy table\n",
        table_markdown,
        "## Accuracy vs. training-set size\n",
    ]
    for dataset, encoder, relative_path in figure_relative_paths:
        report_lines.append(f"### {dataset} / {encoder}\n")
        report_lines.append(f"![{dataset} {encoder} accuracy vs shot]({relative_path.as_posix()})\n")

    report_path = PROJECT_ROOT / "RESULTS.md"
    with open(report_path, "w", encoding="utf-8") as f:
        f.write("\n".join(report_lines))
    print(f"Saved report to {report_path}")


if __name__ == "__main__":
    main()
